### PR TITLE
Design Document - Part II API

### PR DESCRIPTION
**Pull request by pdarsh58**

### CODE REVIEW

**Comment by bryanreiter** [comment]
Let's hold off on pulling, still needs some fine-tuning, some things still need descriptions.

**Comment by pdarsh58** [comment]
Oh ok

**Comment by pdarsh58** [comment]
Professor posted two past Design doc it had one line description for most things, so I also put one description

**Comment by bryanreiter** [comment]
Your descriptions are good, I just noticed some fields were missing some. No worries, I can add those in a little. Otherwise it looks good!

**Review by bryanreiter — APPROVED** [review]
Great work on these docs!

**Pull request merged**
