### PR TITLE
Merging gesture ticket, adding upgraded model to main branch and removing the unnecessary output from other files

### PR DESCRIPTION
**Pull request by Caseymonroe1**

### CODE REVIEW

**Review by bryanreiter — APPROVED** [review]
Looks good casey

**Review by jzcodess — DISMISSED** [review]
looks good

**Review by bryanreiter — APPROVED** [review]
LGTM

**Comment by KevinXJarema** [comment]
Looks good!

**Review by pdarsh58 — APPROVED** [review]
Nice work

**Review by pdarsh58 — APPROVED** [review]
Nice work!

**Review by pdarsh58 — APPROVED** [review]
Nice work!

**Review by pdarsh58 — APPROVED** [review]
Good work!

**Review by bryanreiter — APPROVED** [review]
good work everyone, let's merge it with main!

**Pull request merged**
